## Emacs, make this -*- mode: sh; -*-

FROM rhub/debian

RUN apt-get update && apt-get install -y \
         clang                           \
         gfortran                        \
	 libstdc++-11-dev
